# Generated by Django 5.0.6 on 2024-06-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='max 100 characters', max_length=100, verbose_name='Title of the blog cart')),
                ('datetime', models.DateTimeField(verbose_name='datetime of the blog cart')),
                ('image', models.ImageField(upload_to='', verbose_name='Image of the blog cart')),
                ('description', models.TextField(verbose_name='Text of the blog cart')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is published?')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
