# Generated by Django 5.0.6 on 2024-06-29 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='datetime',
        ),
    ]
