# Generated by Django 5.0.6 on 2024-06-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='max 100 characters', max_length=100, verbose_name='Title of the cart')),
                ('image', models.ImageField(upload_to='', verbose_name='Image of the cart')),
                ('price', models.IntegerField(verbose_name='Price of the cart')),
                ('cart_type', models.IntegerField(choices=[(0, 'Choose'), (1, 'New Arrivals'), (2, 'Laptop'), (3, 'Smartphone'), (4, 'Tablet')], default=0, verbose_name='Type of the cart')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is published?')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'All Carts',
            },
        ),
    ]
