# Generated by Django 5.0.6 on 2024-06-26 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carts',
        ),
    ]
