# Generated by Django 5.0.6 on 2024-06-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='max 100 characters', max_length=100, verbose_name='Title of the cart')),
            ],
            options={
                'verbose_name': 'Product brand',
                'verbose_name_plural': 'All Products brands',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brands',
            field=models.ManyToManyField(related_name='ProductBrand', to='product.brand'),
        ),
    ]
